import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    container: {
      center: true,
      padding: {
        DEFAULT: '1rem',
        sm: '1.5rem',
        lg: '2rem',
      },
      screens: {
        '2xl': '1280px',
      },
    },
    extend: {
      colors: {
        // High-fidelity Design System
        "primary": "#944a00",
        "primary-container": "#f58a31",
        "on-primary": "#ffffff",
        "on-primary-container": "#602e00",
        "primary-fixed": "#ffdcc6",
        "primary-fixed-dim": "#ffb784",
        "on-primary-fixed": "#301400",
        "on-primary-fixed-variant": "#713700",
        "inverse-primary": "#ffb784",

        "secondary": "#2b609b",
        "secondary-container": "#8ebeff",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#0d4c86",
        "secondary-fixed": "#d3e3ff",
        "secondary-fixed-dim": "#a3c9ff",
        "on-secondary-fixed": "#001c39",
        "on-secondary-fixed-variant": "#024882",

        "tertiary": "#006688",
        "tertiary-container": "#00b2ea",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#004057",
        "tertiary-fixed": "#c1e8ff",
        "tertiary-fixed-dim": "#74d1ff",
        "on-tertiary-fixed": "#001e2b",
        "on-tertiary-fixed-variant": "#004d67",

        "background": "#f8f9ff",
        "on-background": "#121c2a",
        "surface": "#f8f9ff",
        "on-surface": "#121c2a",
        "surface-variant": "#d9e3f6",
        "on-surface-variant": "#554337",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#eff4ff",
        "surface-container": "#e6eeff",
        "surface-container-high": "#dee9fc",
        "surface-container-highest": "#d9e3f6",
        "surface-dim": "#d0dbed",
        "surface-bright": "#f8f9ff",
        "inverse-surface": "#27313f",
        "inverse-on-surface": "#eaf1ff",
        "surface-tint": "#944a00",

        "outline": "#897365",
        "outline-variant": "#dcc1b1",

        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",

        // Compatibility aliases with existing components
        brand: {
          primary: '#14508A',
          'primary-hover': '#0E3D6B',
          accent: '#F58A31',
          'accent-hover': '#E07A22',
        },
        canvas: 'var(--bg-canvas)',
        'surface-alt': 'var(--bg-surface-alt)',
        'text-primary': 'var(--text-primary)',
        'text-secondary': 'var(--text-secondary)',
        'text-on-accent': 'var(--text-on-accent)',
        'text-on-primary': 'var(--text-on-primary)',
        'border-subtle': 'var(--border-subtle)',
        'border-strong': 'var(--border-strong)',
        'status-success': 'var(--status-success)',
        'status-success-bg': 'var(--status-success-bg)',
        'status-warning': 'var(--status-warning)',
        'status-warning-bg': 'var(--status-warning-bg)',
        'status-error': 'var(--status-error)',
        'status-error-bg': 'var(--status-error-bg)',
      },
      fontFamily: {
        heading: ['var(--font-space-grotesk)', 'Montserrat', 'sans-serif'],
        body: ['var(--font-plus-jakarta)', 'Inter', 'sans-serif'],
        'display-lg': ['var(--font-space-grotesk)', 'sans-serif'],
        'headline-xl': ['var(--font-space-grotesk)', 'sans-serif'],
        'headline-xl-mobile': ['var(--font-space-grotesk)', 'sans-serif'],
        'headline-lg': ['var(--font-space-grotesk)', 'sans-serif'],
        'headline-md': ['var(--font-space-grotesk)', 'sans-serif'],
        'headline-sm': ['var(--font-space-grotesk)', 'sans-serif'],
        'body-lg': ['var(--font-plus-jakarta)', 'sans-serif'],
        'body-md': ['var(--font-plus-jakarta)', 'sans-serif'],
        'body-sm': ['var(--font-plus-jakarta)', 'sans-serif'],
        'label-lg': ['var(--font-plus-jakarta)', 'sans-serif'],
        'label-md': ['var(--font-plus-jakarta)', 'sans-serif'],
        'label-sm': ['var(--font-plus-jakarta)', 'sans-serif'],
      },
      fontSize: {
        "display-lg": ["56px", { lineHeight: "64px", letterSpacing: "-0.03em", fontWeight: "700" }],
        "display-lg-mobile": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-xl": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-xl-mobile": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "500" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "700" }]
      },
      boxShadow: {
        'ambient': '0 1px 3px rgba(20, 80, 138, 0.04), 0 4px 12px rgba(20, 80, 138, 0.03)',
        'interactive': '0 4px 6px -1px rgba(20, 80, 138, 0.06), 0 12px 24px -4px rgba(20, 80, 138, 0.08)',
        'orange-glow': '0 4px 14px rgba(245, 138, 49, 0.35)',
        'subtle': '0 1px 3px 0 rgba(0, 0, 0, 0.06), 0 1px 2px -1px rgba(0, 0, 0, 0.06)',
        'card': '0 2px 8px -2px rgba(0, 0, 0, 0.08), 0 4px 12px -4px rgba(0, 0, 0, 0.04)',
        'elevated': '0 4px 16px -4px rgba(20, 80, 138, 0.12), 0 8px 24px -8px rgba(20, 80, 138, 0.08)',
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      maxWidth: {
        'prose': '70ch',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
}

export default config
